model: default
model_type: "sat"

pretrain: True
pretrain_path: './weights/sat_hmr/sat_644.pth'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all_sat_pr_sam2_test/epoch_1_step_4509/pytorch_model.bin'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all/epoch_13_step_31569/pytorch_model.bin'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_all_sat_pr_sam2_test/epoch_1_step_23685/pytorch_model.bin'

input_dir: './demo'
output_dir: './demo_results'
conf_thresh: [0.1]
infer_batch_size: 1
infer_num_workers: 8
distributed_infer: True

