model: default

pretrain: True
# pretrain_path: './weights/sat_hmr/sat_644_3dpw.pth'
pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_server_10/pytorch_model.bin'
# pretrain_path: '/home/cglee/SAT-HMR/outputs/ckpts/train_server/pytorch_model.bin'

input_dir: './data/datasets/bedlam/train_images/20221019_3-8_250_highbmihand_orbit_stadium_6fps/png'
output_dir: './tracking_results/bedlam_img_notrkquery'

eval_datasets_used: ['3dpw']
eval_datasets_split: ['test']
eval_vis_num: 20
conf_thresh: [0.1]
eval_batch_size: 1
eval_num_workers: 10
distributed_eval: True

is_gt: False
is_trkquery: False


iou_match_thresh: 0.5
iou_new_thresh: 0.5
is_add_new: True
is_size_filter: False
nms_threshold: 0.7
pr_conf_thresh: 0.9
max_age: 5

total_gpus: 1