model: default

pretrain: True
pretrain_path: './weights/sat_hmr/sat_644_3dpw.pth'

eval_datasets_used: ['3dpw']
eval_datasets_split: ['test']
eval_vis_num: 20
conf_thresh: [0.3]
eval_batch_size: 12
eval_num_workers: 8
distributed_eval: True