input_size: 1288
# input_size: 896
# input_size: 1280
encoder: 'vitb'
# encoder: 'dinov3_vitb'

# decoder
hidden_dim: 768
nheads: 4
dec_layers: 6
dim_feedforward: 2048
dropout: 0.0
num_queries: 50
transformer_activation: "relu"

sat_cfg:
  use_sat: True
  share_patch_embed: False
  preprocess_pos_embed: False
  num_lvls: 3
  lvl_embed: True
  get_map_layer: 3
  use_additional_blocks: True
  conf_thresh: 0.3
  scale_thresh: 0.5

dn_cfg:
  use_dn: True
  dn_number: 1
  tgt_embed_type: "params"
  # tgt_embed_type: "boxes"
  box_noise_scale: 0.4
  tgt_noise_scale: 0.2

LOGDIR: 'lightning_logs'
SEED_VALUE: 0
DEVICES: [0,1,2,3]

MODEL:
  BACKBONE: 'dinov2_vitl14'
  IMG_SIZE: 896
  PATCH_SIZE: 14
  EMBED_DIM: 1024
  MLP_DIM: 1024
  DECODER_DEPTH: 4
  REGRESSOR_DEPTH: 2
  TRANSFORMER: 'cross-person'
  PROMPT_TYPE: 'prompt'
  TRANSL: 'root'
  MASK_PROMPT: True
  INVERSE_DEPTH: True

EXP_NAME: 'fhmr_170'


